version: '3.8'

services:
  webdesa:
    image: php:8.2-apache
    container_name: webdesa
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "3000:80"
    depends_on:
      - mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
