version: "3.8"
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rahasia
      MYSQL_DATABASE: dbku
      MYSQL_USER: userku
      MYSQL_PASSWORD: rahasia

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rahasia
